name: kitahack_2026
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core & Firestore (To read/write messages)
  firebase_core: ^3.15.2
  cloud_firestore: ^5.0.0

  # Gemini AI SDK for Dart (To generate replies instantly)

  # Chat UI (Optional, but saves you 10 hours of UI work)
  # dash_chat_2 is the easiest for hackathons.
  dash_chat_2: ^0.0.18
  flutter_dotenv: ^6.0.0
  firebase_ai: ^2.3.0
  firebase_auth: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/bot_icon.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/bot_icon.png"
