// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFuSlRsZcvU1nssE1JvbLGFLmcLOukg0Q',
    appId: '1:973232530181:web:1cbb28fe922b209a5e8d6c',
    messagingSenderId: '973232530181',
    projectId: 'kitahack-2026-873e9',
    authDomain: 'kitahack-2026-873e9.firebaseapp.com',
    storageBucket: 'kitahack-2026-873e9.firebasestorage.app',
    measurementId: 'G-7FDXQ9ZD8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB052yvKihSPJQMm5PulVKNHxt5lya5so',
    appId: '1:973232530181:android:4c0676ec1df9470f5e8d6c',
    messagingSenderId: '973232530181',
    projectId: 'kitahack-2026-873e9',
    storageBucket: 'kitahack-2026-873e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAKPx5qTRIHRvjYkVTBGn5ijtMypJr_38',
    appId: '1:973232530181:ios:642ada8ccb73f0eb5e8d6c',
    messagingSenderId: '973232530181',
    projectId: 'kitahack-2026-873e9',
    storageBucket: 'kitahack-2026-873e9.firebasestorage.app',
    iosBundleId: 'com.example.proactiveFriend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAKPx5qTRIHRvjYkVTBGn5ijtMypJr_38',
    appId: '1:973232530181:ios:642ada8ccb73f0eb5e8d6c',
    messagingSenderId: '973232530181',
    projectId: 'kitahack-2026-873e9',
    storageBucket: 'kitahack-2026-873e9.firebasestorage.app',
    iosBundleId: 'com.example.proactiveFriend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFuSlRsZcvU1nssE1JvbLGFLmcLOukg0Q',
    appId: '1:973232530181:web:09ef491cd038f55f5e8d6c',
    messagingSenderId: '973232530181',
    projectId: 'kitahack-2026-873e9',
    authDomain: 'kitahack-2026-873e9.firebaseapp.com',
    storageBucket: 'kitahack-2026-873e9.firebasestorage.app',
    measurementId: 'G-4H27EW8PG1',
  );
}
