// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android; // FIX: Now returns the android config below
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ADDED: Manual Android configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFuSlRsZcvU1nssE1JvbLGFLmcLOukg0Q',
    appId: '1:973232530181:android:e7561f736162391b5e8d6c',
    messagingSenderId: '973232530181',
    projectId: 'kitahack-2026-873e9',
    storageBucket: 'kitahack-2026-873e9.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFuSlRsZcvU1nssE1JvbLGFLmcLOukg0Q',
    appId: '1:973232530181:web:09ef491cd038f55f5e8d6c',
    messagingSenderId: '973232530181',
    projectId: 'kitahack-2026-873e9',
    authDomain: 'kitahack-2026-873e9.firebaseapp.com',
    storageBucket: 'kitahack-2026-873e9.firebasestorage.app',
    measurementId: 'G-4H27EW8PG1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAKPx5qTRIHRvjYkVTBGn5ijtMypJr_38',
    appId: '1:973232530181:ios:1225cb5f49742f7c5e8d6c',
    messagingSenderId: '973232530181',
    projectId: 'kitahack-2026-873e9',
    storageBucket: 'kitahack-2026-873e9.firebasestorage.app',
    iosClientId: '973232530181-d7n5q19arbi04rkfrfsle6k19adejbl6.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitahack2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAKPx5qTRIHRvjYkVTBGn5ijtMypJr_38',
    appId: '1:973232530181:ios:1225cb5f49742f7c5e8d6c',
    messagingSenderId: '973232530181',
    projectId: 'kitahack-2026-873e9',
    storageBucket: 'kitahack-2026-873e9.firebasestorage.app',
    iosClientId: '973232530181-d7n5q19arbi04rkfrfsle6k19adejbl6.apps.googleusercontent.com',
    iosBundleId: 'com.example.kitahack2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQYDJFFRzx8kVnkI_pGrHKcZrjCrnIqi8',
    appId: '1:973232530181:web:51364fecd56a5cb75e8d6c',
    messagingSenderId: '973232530181',
    projectId: 'kitahack-2026-873e9',
    authDomain: 'kitahack-2026-873e9.firebaseapp.com',
    storageBucket: 'kitahack-2026-873e9.firebasestorage.app',
    measurementId: 'G-DERSFMVEQB',
  );
}